name: 'Publish'

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: Windows
            triplet: x64-windows-static
          - os: ubuntu-latest
            name: Linux
            triplet: x64-linux-static

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: 'Install CMake'
        uses: lukka/get-cmake@latest
      - name: 'Setup vcpkg'
        uses: lukka/run-vcpkg@v10
        env:
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-vcpkg
